### ISSUE TITLE
「Check URL is valid URL」 is invalid

### ISSUE THREAD

**Issue by KageShiron** [azu/url-cheatsheet#9]
大変興味深い記事をありがとうございます。

> Check [URL](https://developer.mozilla.org/docs/Web/API/URL/URL) is valid URL throw an error when parsing invalid url string.

こちらの記述は、必ずしも適切な表現ではないかと思います。
明確にInvalidな様々なURLを、ブラウザは例外を出さずにパースします。

```
new URL("http://;;;");
```
上記の処理は、ChromeではTypeErrorとなり、Firefoxでは`http://;;;`というURLとしてパースが成功します。
本当にValidなURLかどうかを判断する方法はおそらくこの世に存在しないため、「InvalidなURLの一部をエラーにできる」といった表現が穏当でしょうか…。

**Comment by azu** [comment]
*valid*が曖昧な感じですかね。
Absolute-URL 絶対URLかどうかの判定が良さそうですかね。(URLとしてパースできる は流石になんか意味ない感じに見えてしまう)
https://url.spec.whatwg.org/#constructors

用途はschemeが無かったりhttp//みたいな書きミスを見つけるぐらいで、
実際に入力されたURLを判定するとかの場合は https://github.com/azu/url-cheatsheet#check-url-is-http の方を使うという感じな気もしますね。
(httpじゃないURLを扱うケースはそこまで多くもないので)

**Comment by azu** [comment]
https://github.com/whatwg/url/issues/713 でも似た話がありました
